### ISSUE TITLE
Per channel stereo outputs (multi-channel support)

### ISSUE THREAD

**Issue by danvd** [harryhaaren/openAV-Fabla#37]
Hi Harry!

Do you plan to add per-sample audio out ports? Instead of implementing internal effects, one can route each sample to host's bus and apply effects here :)

Regards,
Andrew.

**Comment by danvd** [comment]
Hi @harryhaaren!

Since this issue is still open, I can say, that I made multi out patch some time ago. Applying it to current git master (after a commit made on Nov 4 2014) will bring 34 mono (18 stereo) outputs, i.e -  1 stereo mix + 16 stereo outputs (one per channel). The final channel map will be:
1. L+R - Stereo mix (as before) (with compressor effect)
2. L+R - Channel 1
3. L+R - Channel 2
etc..
All individual channels are exported without compressor applyed, only final mix will use it.
Here is a link to a sample melody made with multi channel Fabla:
http://youtu.be/AMklg13KI8Q
Only 5 samples are used. They are routed to individial host busses. 
Bass drum + clap are routed to control input of sidechain compressor (for compressing bass),
Hat is routed to a delay line.
Clap is also routed to another delay line.

P.S. All projects made with non-multi Fabla are backwards-compatible.

I've created new pull request, it's up to you, Harry merge it or not, but anyway, may be this patch will be useful for somebody. Here is the link to request:
https://github.com/harryhaaren/openAV-Fabla/pull/39

Regards,
Andrew.

**Comment by harryhaaren** [comment]
Hi Andrew,

Thanks for posting the patch, indeed some users might wish to build this version themselves.

I won't merge this: and it is because this is *not* backwards compatible. Some hosts *do not* handle *anything* except mono or stereo out: I'm sure you would agree breaking backwards compatibility for these hosts is a bad idea. 

PACKAGERS: please do *NOT* package this: it breaks backwards compatibility.

I'll close this issue now. Thanks for your contribution to Fabla, I'm happy to refer any users who ask for this feature to your patch. Please do not release or package your patch, as it breaks backwards compatibility with the existing released Fabla.

Fabla2 will fix the issue busses, so a fix is on the way.  Thanks again, -Harry

PS: Nice music in the video!

**Comment by ViktorNova** [comment]
Just wanted to chime in and say thank you to @danvd for putting this patch up - I will definitely be merging it into a branch of one of my forks and using it in the studio!

To add my story to the conversation - my band has been using Fabla 1 live (currently have 6 global instances running at all times, for each song) and are now in the studio working on the album, so I need an individual stereo wave render for each drum sample - I don't even need to explain why multi-out is needed in this situation =)

**Comment by harryhaaren** [comment]
Hi @ViktorNova, cool I'm happy Fabla is useful for you, and also that Dan posted his patches - the beauty of open source :)

Do you have any videos of what you're using Fabla for live? I'd like to see! -Harry

**Comment by ViktorNova** [comment]
Hey @harryhaaren , thanks for asking! Sadly no videos yet, but I will share them with you as soon as we get some =D
